// list of all possible enums in child component
const PRODUCT_CALLBACK_ENUMS = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    ADD_NEW_PRODUCT: 'ADD_NEW_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
};

export {
    PRODUCT_CALLBACK_ENUMS,
};